# Generated by Django 4.2.7 on 2025-11-15 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=100)),
                ('level', models.CharField(max_length=100)),
                ('class_name', models.CharField(max_length=100)),
                ('due_date', models.DateField()),
                ('total_marks', models.IntegerField()),
                ('num_questions', models.IntegerField()),
                ('instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=200)),
                ('answer_file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('answer_text', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('written_score', models.IntegerField(default=0)),
                ('interview_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('overall_strengths', models.TextField(blank=True)),
                ('overall_improvements', models.TextField(blank=True)),
                ('analysis_completed_at', models.DateTimeField(blank=True, null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.homework')),
            ],
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_topics', models.TextField()),
                ('strength_topics', models.TextField()),
                ('written_vs_verbal_analysis', models.TextField()),
                ('learning_style_insights', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan', to='core.submission')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('video_url', models.CharField(blank=True, max_length=500)),
                ('recording', models.FileField(blank=True, null=True, upload_to='interview_recordings/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('problem_solving_score', models.IntegerField(default=0)),
                ('conceptual_understanding_score', models.IntegerField(default=0)),
                ('creative_application_score', models.IntegerField(default=0)),
                ('strong_moments', models.TextField(blank=True)),
                ('development_areas', models.TextField(blank=True)),
                ('overall_analysis', models.TextField(blank=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interview', to='core.submission')),
            ],
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_type', models.CharField(max_length=50)),
                ('question_text', models.TextField()),
                ('response_quality', models.IntegerField(default=0)),
                ('response_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.interviewsession')),
            ],
            options={
                'ordering': ['question_number'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('questions', 'Questions'), ('mark_scheme', 'Mark Scheme'), ('model_answers', 'Model Answers'), ('textbook', 'Textbook')], max_length=20)),
                ('file', models.FileField(upload_to='homework_files/')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.homework')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question_title', models.CharField(max_length=200)),
                ('marks_awarded', models.IntegerField()),
                ('marks_total', models.IntegerField()),
                ('percentage', models.IntegerField()),
                ('strengths', models.TextField()),
                ('improvements', models.TextField()),
                ('detailed_analysis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_feedbacks', to='core.submission')),
            ],
            options={
                'ordering': ['question_number'],
                'unique_together': {('submission', 'question_number')},
            },
        ),
    ]
