# Generated by Django 4.2.7 on 2025-11-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewsession',
            name='transcription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
